#数据库连接
SQL:
  Url: "localhost:3306"
  Name: "root"
  Password: "test123"
  Database: "test?autoReconnect=true&useSSL=false&maxReconnects=10"
#消息
Message:
  success: "&a&l你锻造了出了 {item} 本次获得{exp} 点锻造经验！"
#锻造UI名字
Title: "&e&l锻造台"
#锻造等级
Levels:
  1:
    #变量 %wsforge_name%
    name: "初级锻造师"
    #所需经验
    exp: 100
    #锻造品质提升值 公式: 原始值 + 提升值 = 最终锻造值
    quality:
      bai: 30
      lv: 20
      lan: 10
      zi: 5
      hong: 3
      jin: 1
  2:
    #所需经验
    #变量 %wsforge_name%
    name: "中级锻造师"
    exp: 100
    #锻造品质提升值 公式: 原始值 + 提升值 = 最终锻造值
    quality:
      bai: 30
      lv: 40
      lan: 30
      zi: 20
      hong: 10
      jin: 5